// This file was generated by liblab | https://liblab.com/

import { Environment } from './http/environment';
import { SdkConfig } from './http/types';
import { PetService } from './services/pet';
import { StoreService } from './services/store';
import { UserService } from './services/user';

export * from './services/pet';
export * from './services/store';
export * from './services/user';

export type * from './http';

export class SwaggerPetstoreOpenApi3_0 {
  public readonly pet: PetService;

  public readonly store: StoreService;

  public readonly user: UserService;

  constructor(public config: SdkConfig) {
    const baseUrl = config.environment || config.baseUrl || Environment.DEFAULT;
    this.config = {
      ...config,
      baseUrl,
    };
    this.pet = new PetService(this.config);

    this.store = new StoreService(this.config);

    this.user = new UserService(this.config);
  }

  set baseUrl(baseUrl: string) {
    this.pet.baseUrl = baseUrl;
    this.store.baseUrl = baseUrl;
    this.user.baseUrl = baseUrl;
  }

  set environment(environment: Environment) {
    this.pet.baseUrl = environment;
    this.store.baseUrl = environment;
    this.user.baseUrl = environment;
  }

  set timeoutMs(timeoutMs: number) {
    this.pet.timeoutMs = timeoutMs;
    this.store.timeoutMs = timeoutMs;
    this.user.timeoutMs = timeoutMs;
  }

  set token(token: string) {
    this.pet.token = token;
    this.store.token = token;
    this.user.token = token;
  }
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
