// This file was generated by liblab | https://liblab.com/

import { SwaggerPetstoreOpenApi3_0 } from 'swaggerpetstore';

(async () => {
  const swaggerPetstoreOpenApi3_0 = new SwaggerPetstoreOpenApi3_0({
    token: 'YOUR_TOKEN',
  });

  const findPetsByStatusStatus = 'available';

  // const { data } = await swaggerPetstoreOpenApi3_0.pet.findPetsByStatus({
  //   status: findPetsByStatusStatus,
  // });

  // console.log(data);

  const { data } = await swaggerPetstoreOpenApi3_0.user.loginUser({
    username: 'username',
    password: 'password',
  });
  console.log(data);
})();
