# This file was generated by liblab | https://liblab.com/

from enum import Enum


class FindPetsByStatusStatus(Enum):
    """An enumeration representing different categories.

    :cvar AVAILABLE: "available"
    :vartype AVAILABLE: str
    :cvar PENDING: "pending"
    :vartype PENDING: str
    :cvar SOLD: "sold"
    :vartype SOLD: str
    """

    AVAILABLE = "available"
    PENDING = "pending"
    SOLD = "sold"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, FindPetsByStatusStatus._member_map_.values())
        )
