// This file was generated by liblab | https://liblab.com/

import { FindPetsByStatusStatus, findPetsByStatusStatus } from './models/find-pets-by-status-status';

export interface FindPetsByStatusParams {
  status?: FindPetsByStatusStatus;
}

export interface FindPetsByTagsParams {
  tags?: string[];
}

export interface UpdatePetWithFormParams {
  name?: string;
  status?: string;
}

export interface DeletePetParams {
  apiKey?: string;
}

export interface UploadFileParams {
  additionalMetadata?: string;
}
