// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const orderStatus = z.union([z.literal('placed'), z.literal('approved'), z.literal('delivered')]);

export type OrderStatus = z.infer<typeof orderStatus>;
