// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const findPetsByStatusStatus = z.union([z.literal('available'), z.literal('pending'), z.literal('sold')]);

export type FindPetsByStatusStatus = z.infer<typeof findPetsByStatusStatus>;
