// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const petStatus = z.union([z.literal('available'), z.literal('pending'), z.literal('sold')]);

export type PetStatus = z.infer<typeof petStatus>;
