# This file was generated by liblab | https://liblab.com/

from swagger_petstore_open_api_3_0 import SwaggerPetstoreOpenApi3_0
from swagger_petstore_open_api_3_0.models import FindPetsByStatusStatus

sdk = SwaggerPetstoreOpenApi3_0(access_token="YOUR_ACCESS_TOKEN", timeout=10000)

result = sdk.pet.find_pets_by_status(status="available")

with open("output-file.ext", "w") as f:
    f.write(result)
