# This file was generated by liblab | https://liblab.com/

from typing import Union
from .services.pet import PetService
from .services.store import StoreService
from .services.user import UserService
from .net.environment import Environment


class SwaggerPetstoreOpenApi3_0:
    def __init__(
        self,
        access_token: str = None,
        base_url: Union[Environment, str] = Environment.DEFAULT,
        timeout: int = 60000,
    ):
        """
        Initializes SwaggerPetstoreOpenApi3_0 the SDK class.
        """

        self._base_url = (
            base_url.value if isinstance(base_url, Environment) else base_url
        )
        self.pet = PetService(base_url=self._base_url)
        self.store = StoreService(base_url=self._base_url)
        self.user = UserService(base_url=self._base_url)
        self.set_access_token(access_token)
        self.set_timeout(timeout)

    def set_base_url(self, base_url: Union[Environment, str]):
        """
        Sets the base URL for the entire SDK.

        :param Union[Environment, str] base_url: The base URL to be set.
        :return: The SDK instance.
        """
        self._base_url = (
            base_url.value if isinstance(base_url, Environment) else base_url
        )

        self.pet.set_base_url(self._base_url)
        self.store.set_base_url(self._base_url)
        self.user.set_base_url(self._base_url)

        return self

    def set_access_token(self, access_token: str):
        """
        Sets the access token for the entire SDK.
        """
        self.pet.set_access_token(access_token)
        self.store.set_access_token(access_token)
        self.user.set_access_token(access_token)

        return self

    def set_timeout(self, timeout: int):
        """
        Sets the timeout for the entire SDK.

        :param int timeout: The timeout (ms) to be set.
        :return: The SDK instance.
        """
        self.pet.set_timeout(timeout)
        self.store.set_timeout(timeout)
        self.user.set_timeout(timeout)

        return self


# c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
